name: rdbms

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-default}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./queries:/docker-entrypoint-initdb.d
    networks:
      - default
      - rsm-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "${POSTGRES_DB:-default}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    command:
      -c shared_buffers=512MB
      -c work_mem=32MB

volumes:
  db-data:

networks:
  rsm-network:
    external: true