CREATE TABLE IF NOT EXISTS ${SCHEMA}.${LANDING_TABLE} (
    batch_id UUID NOT NULL,
    batch_extraction_start TIMESTAMP NOT NULL,
    property_id UUID NOT NULL,
    property_extraction_start TIMESTAMP NOT NULL,
    property_type VARCHAR,
    price_type VARCHAR,
    price_pen DECIMAL(19, 2),
    price_usd DECIMAL(19, 2),
    additional_expense DECIMAL(19, 2),
    address VARCHAR,
	region VARCHAR,
	city VARCHAR,
    district VARCHAR,
    total_size INT,
    covered_size INT,
    bedrooms INT,
    bathrooms INT,
    half_bathrooms INT,
    parking_spaces INT,
    age INT,
    link VARCHAR,
	created_at TIMESTAMP  NOT NULL DEFAULT NOW(),
	created_by VARCHAR NOT NULL DEFAULT CURRENT_USER,
	PRIMARY KEY (batch_id, property_id)
);